// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// CSplitRowsByCode
List CSplitRowsByCode(IntegerVector codes, int nlevels);
RcppExport SEXP _drake_CSplitRowsByCode(SEXP codesSEXP, SEXP nlevelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type codes(codesSEXP);
    Rcpp::traits::input_parameter< int >::type nlevels(nlevelsSEXP);
    rcpp_result_gen = Rcpp::wrap(CSplitRowsByCode(codes, nlevels));
    return rcpp_result_gen;
END_RCPP
}
// CClampWeights
NumericVector CClampWeights(NumericVector weights, double max_weight, double min_weight);
RcppExport SEXP _drake_CClampWeights(SEXP weightsSEXP, SEXP max_weightSEXP, SEXP min_weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type max_weight(max_weightSEXP);
    Rcpp::traits::input_parameter< double >::type min_weight(min_weightSEXP);
    rcpp_result_gen = Rcpp::wrap(CClampWeights(weights, max_weight, min_weight));
    return rcpp_result_gen;
END_RCPP
}
// CApplyDensityTarget
NumericVector CApplyDensityTarget(NumericVector weights, IntegerVector match_index, NumericVector sample_y, NumericVector target_y);
RcppExport SEXP _drake_CApplyDensityTarget(SEXP weightsSEXP, SEXP match_indexSEXP, SEXP sample_ySEXP, SEXP target_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type match_index(match_indexSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sample_y(sample_ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target_y(target_ySEXP);
    rcpp_result_gen = Rcpp::wrap(CApplyDensityTarget(weights, match_index, sample_y, target_y));
    return rcpp_result_gen;
END_RCPP
}
// CContinuousDiffFromDensity
double CContinuousDiffFromDensity(NumericVector sample_y, NumericVector target_y);
RcppExport SEXP _drake_CContinuousDiffFromDensity(SEXP sample_ySEXP, SEXP target_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type sample_y(sample_ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target_y(target_ySEXP);
    rcpp_result_gen = Rcpp::wrap(CContinuousDiffFromDensity(sample_y, target_y));
    return rcpp_result_gen;
END_RCPP
}
// CBuildGaussianBasis
NumericMatrix CBuildGaussianBasis(NumericVector x, NumericVector xout, double bw);
RcppExport SEXP _drake_CBuildGaussianBasis(SEXP xSEXP, SEXP xoutSEXP, SEXP bwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xout(xoutSEXP);
    Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    rcpp_result_gen = Rcpp::wrap(CBuildGaussianBasis(x, xout, bw));
    return rcpp_result_gen;
END_RCPP
}
// CWeightByContinuousBasis
NumericVector CWeightByContinuousBasis(NumericVector weights, NumericMatrix basis, IntegerVector match_index, NumericVector target_y);
RcppExport SEXP _drake_CWeightByContinuousBasis(SEXP weightsSEXP, SEXP basisSEXP, SEXP match_indexSEXP, SEXP target_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type basis(basisSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type match_index(match_indexSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target_y(target_ySEXP);
    rcpp_result_gen = Rcpp::wrap(CWeightByContinuousBasis(weights, basis, match_index, target_y));
    return rcpp_result_gen;
END_RCPP
}
// CContinuousBasisDiff
double CContinuousBasisDiff(NumericVector weights, NumericMatrix basis, NumericVector target_y);
RcppExport SEXP _drake_CContinuousBasisDiff(SEXP weightsSEXP, SEXP basisSEXP, SEXP target_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type basis(basisSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target_y(target_ySEXP);
    rcpp_result_gen = Rcpp::wrap(CContinuousBasisDiff(weights, basis, target_y));
    return rcpp_result_gen;
END_RCPP
}
// CWeightByContinuousGaussian
NumericVector CWeightByContinuousGaussian(NumericVector x, NumericVector weights, NumericVector xout, double bw, IntegerVector match_index, NumericVector target_y);
RcppExport SEXP _drake_CWeightByContinuousGaussian(SEXP xSEXP, SEXP weightsSEXP, SEXP xoutSEXP, SEXP bwSEXP, SEXP match_indexSEXP, SEXP target_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xout(xoutSEXP);
    Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type match_index(match_indexSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target_y(target_ySEXP);
    rcpp_result_gen = Rcpp::wrap(CWeightByContinuousGaussian(x, weights, xout, bw, match_index, target_y));
    return rcpp_result_gen;
END_RCPP
}
// CContinuousGaussianDiff
double CContinuousGaussianDiff(NumericVector x, NumericVector weights, NumericVector xout, double bw, NumericVector target_y);
RcppExport SEXP _drake_CContinuousGaussianDiff(SEXP xSEXP, SEXP weightsSEXP, SEXP xoutSEXP, SEXP bwSEXP, SEXP target_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xout(xoutSEXP);
    Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target_y(target_ySEXP);
    rcpp_result_gen = Rcpp::wrap(CContinuousGaussianDiff(x, weights, xout, bw, target_y));
    return rcpp_result_gen;
END_RCPP
}
// CWeightByDiscreteMany
NumericVector CWeightByDiscreteMany(List codes_list, NumericVector weights, List targets_list, bool cap_every_var, double max_weight, double min_weight);
RcppExport SEXP _drake_CWeightByDiscreteMany(SEXP codes_listSEXP, SEXP weightsSEXP, SEXP targets_listSEXP, SEXP cap_every_varSEXP, SEXP max_weightSEXP, SEXP min_weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type codes_list(codes_listSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< List >::type targets_list(targets_listSEXP);
    Rcpp::traits::input_parameter< bool >::type cap_every_var(cap_every_varSEXP);
    Rcpp::traits::input_parameter< double >::type max_weight(max_weightSEXP);
    Rcpp::traits::input_parameter< double >::type min_weight(min_weightSEXP);
    rcpp_result_gen = Rcpp::wrap(CWeightByDiscreteMany(codes_list, weights, targets_list, cap_every_var, max_weight, min_weight));
    return rcpp_result_gen;
END_RCPP
}
// CMaxAbsDiscreteDiffMany
double CMaxAbsDiscreteDiffMany(List codes_list, NumericVector weights, List targets_list);
RcppExport SEXP _drake_CMaxAbsDiscreteDiffMany(SEXP codes_listSEXP, SEXP weightsSEXP, SEXP targets_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type codes_list(codes_listSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< List >::type targets_list(targets_listSEXP);
    rcpp_result_gen = Rcpp::wrap(CMaxAbsDiscreteDiffMany(codes_list, weights, targets_list));
    return rcpp_result_gen;
END_RCPP
}
// CWeightByDiscreteSubsetMany
NumericVector CWeightByDiscreteSubsetMany(List target_code_list, List strata_code_list, NumericVector weights, List targets_by_strata_list, bool cap_every_var, double max_weight, double min_weight);
RcppExport SEXP _drake_CWeightByDiscreteSubsetMany(SEXP target_code_listSEXP, SEXP strata_code_listSEXP, SEXP weightsSEXP, SEXP targets_by_strata_listSEXP, SEXP cap_every_varSEXP, SEXP max_weightSEXP, SEXP min_weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type target_code_list(target_code_listSEXP);
    Rcpp::traits::input_parameter< List >::type strata_code_list(strata_code_listSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< List >::type targets_by_strata_list(targets_by_strata_listSEXP);
    Rcpp::traits::input_parameter< bool >::type cap_every_var(cap_every_varSEXP);
    Rcpp::traits::input_parameter< double >::type max_weight(max_weightSEXP);
    Rcpp::traits::input_parameter< double >::type min_weight(min_weightSEXP);
    rcpp_result_gen = Rcpp::wrap(CWeightByDiscreteSubsetMany(target_code_list, strata_code_list, weights, targets_by_strata_list, cap_every_var, max_weight, min_weight));
    return rcpp_result_gen;
END_RCPP
}
// CWeightByDiscreteCodes
NumericVector CWeightByDiscreteCodes(IntegerVector codes, NumericVector weights, NumericVector targets);
RcppExport SEXP _drake_CWeightByDiscreteCodes(SEXP codesSEXP, SEXP weightsSEXP, SEXP targetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type codes(codesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type targets(targetsSEXP);
    rcpp_result_gen = Rcpp::wrap(CWeightByDiscreteCodes(codes, weights, targets));
    return rcpp_result_gen;
END_RCPP
}
// CMaxAbsDiscreteDiff
double CMaxAbsDiscreteDiff(IntegerVector codes, NumericVector weights, NumericVector targets);
RcppExport SEXP _drake_CMaxAbsDiscreteDiff(SEXP codesSEXP, SEXP weightsSEXP, SEXP targetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type codes(codesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type targets(targetsSEXP);
    rcpp_result_gen = Rcpp::wrap(CMaxAbsDiscreteDiff(codes, weights, targets));
    return rcpp_result_gen;
END_RCPP
}
// CWeightByDiscreteSubsetCodes
NumericVector CWeightByDiscreteSubsetCodes(IntegerVector target_codes, IntegerVector strata_codes, NumericVector weights, NumericMatrix targets_by_strata);
RcppExport SEXP _drake_CWeightByDiscreteSubsetCodes(SEXP target_codesSEXP, SEXP strata_codesSEXP, SEXP weightsSEXP, SEXP targets_by_strataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type target_codes(target_codesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type strata_codes(strata_codesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type targets_by_strata(targets_by_strataSEXP);
    rcpp_result_gen = Rcpp::wrap(CWeightByDiscreteSubsetCodes(target_codes, strata_codes, weights, targets_by_strata));
    return rcpp_result_gen;
END_RCPP
}
// CMaxAbsDiscreteSubsetDiff
double CMaxAbsDiscreteSubsetDiff(IntegerVector target_codes, IntegerVector strata_codes, NumericVector weights, NumericMatrix targets_by_strata);
RcppExport SEXP _drake_CMaxAbsDiscreteSubsetDiff(SEXP target_codesSEXP, SEXP strata_codesSEXP, SEXP weightsSEXP, SEXP targets_by_strataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type target_codes(target_codesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type strata_codes(strata_codesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type targets_by_strata(targets_by_strataSEXP);
    rcpp_result_gen = Rcpp::wrap(CMaxAbsDiscreteSubsetDiff(target_codes, strata_codes, weights, targets_by_strata));
    return rcpp_result_gen;
END_RCPP
}
// HiFunction
double HiFunction(double k, NumericVector hivw, NumericVector lovw, NumericVector hidiff, NumericVector lodiff, NumericVector loweight, NumericVector hiweight, double meantarget, int hilength, int lolength);
RcppExport SEXP _drake_HiFunction(SEXP kSEXP, SEXP hivwSEXP, SEXP lovwSEXP, SEXP hidiffSEXP, SEXP lodiffSEXP, SEXP loweightSEXP, SEXP hiweightSEXP, SEXP meantargetSEXP, SEXP hilengthSEXP, SEXP lolengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hivw(hivwSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lovw(lovwSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hidiff(hidiffSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lodiff(lodiffSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type loweight(loweightSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hiweight(hiweightSEXP);
    Rcpp::traits::input_parameter< double >::type meantarget(meantargetSEXP);
    Rcpp::traits::input_parameter< int >::type hilength(hilengthSEXP);
    Rcpp::traits::input_parameter< int >::type lolength(lolengthSEXP);
    rcpp_result_gen = Rcpp::wrap(HiFunction(k, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength));
    return rcpp_result_gen;
END_RCPP
}
// LoFunction
double LoFunction(double k, NumericVector hivw, NumericVector lovw, NumericVector hidiff, NumericVector lodiff, NumericVector loweight, NumericVector hiweight, double meantarget, int hilength, int lolength);
RcppExport SEXP _drake_LoFunction(SEXP kSEXP, SEXP hivwSEXP, SEXP lovwSEXP, SEXP hidiffSEXP, SEXP lodiffSEXP, SEXP loweightSEXP, SEXP hiweightSEXP, SEXP meantargetSEXP, SEXP hilengthSEXP, SEXP lolengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hivw(hivwSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lovw(lovwSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hidiff(hidiffSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lodiff(lodiffSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type loweight(loweightSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hiweight(hiweightSEXP);
    Rcpp::traits::input_parameter< double >::type meantarget(meantargetSEXP);
    Rcpp::traits::input_parameter< int >::type hilength(hilengthSEXP);
    Rcpp::traits::input_parameter< int >::type lolength(lolengthSEXP);
    rcpp_result_gen = Rcpp::wrap(LoFunction(k, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength));
    return rcpp_result_gen;
END_RCPP
}
// LoZero
double LoZero(double a, double b, double t, NumericVector hivw, NumericVector lovw, NumericVector hidiff, NumericVector lodiff, NumericVector loweight, NumericVector hiweight, double meantarget, int hilength, int lolength);
RcppExport SEXP _drake_LoZero(SEXP aSEXP, SEXP bSEXP, SEXP tSEXP, SEXP hivwSEXP, SEXP lovwSEXP, SEXP hidiffSEXP, SEXP lodiffSEXP, SEXP loweightSEXP, SEXP hiweightSEXP, SEXP meantargetSEXP, SEXP hilengthSEXP, SEXP lolengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hivw(hivwSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lovw(lovwSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hidiff(hidiffSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lodiff(lodiffSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type loweight(loweightSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hiweight(hiweightSEXP);
    Rcpp::traits::input_parameter< double >::type meantarget(meantargetSEXP);
    Rcpp::traits::input_parameter< int >::type hilength(hilengthSEXP);
    Rcpp::traits::input_parameter< int >::type lolength(lolengthSEXP);
    rcpp_result_gen = Rcpp::wrap(LoZero(a, b, t, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength));
    return rcpp_result_gen;
END_RCPP
}
// HiZero
double HiZero(double a, double b, double t, NumericVector hivw, NumericVector lovw, NumericVector hidiff, NumericVector lodiff, NumericVector loweight, NumericVector hiweight, double meantarget, int hilength, int lolength);
RcppExport SEXP _drake_HiZero(SEXP aSEXP, SEXP bSEXP, SEXP tSEXP, SEXP hivwSEXP, SEXP lovwSEXP, SEXP hidiffSEXP, SEXP lodiffSEXP, SEXP loweightSEXP, SEXP hiweightSEXP, SEXP meantargetSEXP, SEXP hilengthSEXP, SEXP lolengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hivw(hivwSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lovw(lovwSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hidiff(hidiffSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lodiff(lodiffSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type loweight(loweightSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hiweight(hiweightSEXP);
    Rcpp::traits::input_parameter< double >::type meantarget(meantargetSEXP);
    Rcpp::traits::input_parameter< int >::type hilength(hilengthSEXP);
    Rcpp::traits::input_parameter< int >::type lolength(lolengthSEXP);
    rcpp_result_gen = Rcpp::wrap(HiZero(a, b, t, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength));
    return rcpp_result_gen;
END_RCPP
}
// CWeightByMeanLinear
NumericVector CWeightByMeanLinear(NumericVector weight, NumericVector var, double meantarget);
RcppExport SEXP _drake_CWeightByMeanLinear(SEXP weightSEXP, SEXP varSEXP, SEXP meantargetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type var(varSEXP);
    Rcpp::traits::input_parameter< double >::type meantarget(meantargetSEXP);
    rcpp_result_gen = Rcpp::wrap(CWeightByMeanLinear(weight, var, meantarget));
    return rcpp_result_gen;
END_RCPP
}
// anyIsNA
bool anyIsNA(NumericVector x);
RcppExport SEXP _drake_anyIsNA(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(anyIsNA(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_drake_CSplitRowsByCode", (DL_FUNC) &_drake_CSplitRowsByCode, 2},
    {"_drake_CClampWeights", (DL_FUNC) &_drake_CClampWeights, 3},
    {"_drake_CApplyDensityTarget", (DL_FUNC) &_drake_CApplyDensityTarget, 4},
    {"_drake_CContinuousDiffFromDensity", (DL_FUNC) &_drake_CContinuousDiffFromDensity, 2},
    {"_drake_CBuildGaussianBasis", (DL_FUNC) &_drake_CBuildGaussianBasis, 3},
    {"_drake_CWeightByContinuousBasis", (DL_FUNC) &_drake_CWeightByContinuousBasis, 4},
    {"_drake_CContinuousBasisDiff", (DL_FUNC) &_drake_CContinuousBasisDiff, 3},
    {"_drake_CWeightByContinuousGaussian", (DL_FUNC) &_drake_CWeightByContinuousGaussian, 6},
    {"_drake_CContinuousGaussianDiff", (DL_FUNC) &_drake_CContinuousGaussianDiff, 5},
    {"_drake_CWeightByDiscreteMany", (DL_FUNC) &_drake_CWeightByDiscreteMany, 6},
    {"_drake_CMaxAbsDiscreteDiffMany", (DL_FUNC) &_drake_CMaxAbsDiscreteDiffMany, 3},
    {"_drake_CWeightByDiscreteSubsetMany", (DL_FUNC) &_drake_CWeightByDiscreteSubsetMany, 7},
    {"_drake_CWeightByDiscreteCodes", (DL_FUNC) &_drake_CWeightByDiscreteCodes, 3},
    {"_drake_CMaxAbsDiscreteDiff", (DL_FUNC) &_drake_CMaxAbsDiscreteDiff, 3},
    {"_drake_CWeightByDiscreteSubsetCodes", (DL_FUNC) &_drake_CWeightByDiscreteSubsetCodes, 4},
    {"_drake_CMaxAbsDiscreteSubsetDiff", (DL_FUNC) &_drake_CMaxAbsDiscreteSubsetDiff, 4},
    {"_drake_HiFunction", (DL_FUNC) &_drake_HiFunction, 10},
    {"_drake_LoFunction", (DL_FUNC) &_drake_LoFunction, 10},
    {"_drake_LoZero", (DL_FUNC) &_drake_LoZero, 12},
    {"_drake_HiZero", (DL_FUNC) &_drake_HiZero, 12},
    {"_drake_CWeightByMeanLinear", (DL_FUNC) &_drake_CWeightByMeanLinear, 3},
    {"_drake_anyIsNA", (DL_FUNC) &_drake_anyIsNA, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_drake(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
