# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

if(!"Rcpp" %in% loadedNamespaces()) {
    loadNamespace("Rcpp")
}

CWeightByDiscreteCodes <- function(codes, weights, targets) {
    .Call("_drake_CWeightByDiscreteCodes", PACKAGE = "drake", codes, weights, targets)
}

CMaxAbsDiscreteDiff <- function(codes, weights, targets) {
    .Call("_drake_CMaxAbsDiscreteDiff", PACKAGE = "drake", codes, weights, targets)
}

CWeightByDiscreteSubsetCodes <- function(target_codes, strata_codes, weights, targets_by_strata) {
    .Call("_drake_CWeightByDiscreteSubsetCodes", PACKAGE = "drake", target_codes, strata_codes, weights, targets_by_strata)
}

CMaxAbsDiscreteSubsetDiff <- function(target_codes, strata_codes, weights, targets_by_strata) {
    .Call("_drake_CMaxAbsDiscreteSubsetDiff", PACKAGE = "drake", target_codes, strata_codes, weights, targets_by_strata)
}

HiFunction <- function(k, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength) {
    .Call("_drake_HiFunction", PACKAGE = "drake", k, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength)
}

LoFunction <- function(k, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength) {
    .Call("_drake_LoFunction", PACKAGE = "drake", k, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength)
}

LoZero <- function(a, b, t, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength) {
    .Call("_drake_LoZero", PACKAGE = "drake", a, b, t, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength)
}

HiZero <- function(a, b, t, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength) {
    .Call("_drake_HiZero", PACKAGE = "drake", a, b, t, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength)
}

CWeightByMeanLinear <- function(weight, var, meantarget) {
    .Call("_drake_CWeightByMeanLinear", PACKAGE = "drake", weight, var, meantarget)
}

anyIsNA <- function(x) {
    .Call("_drake_anyIsNA", PACKAGE = "drake", x)
}
