# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HiFunction <- function(k, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength) {
    .Call('_drake_HiFunction', PACKAGE = 'drake', k, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength)
}

LoFunction <- function(k, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength) {
    .Call('_drake_LoFunction', PACKAGE = 'drake', k, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength)
}

LoZero <- function(a, b, t, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength) {
    .Call('_drake_LoZero', PACKAGE = 'drake', a, b, t, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength)
}

HiZero <- function(a, b, t, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength) {
    .Call('_drake_HiZero', PACKAGE = 'drake', a, b, t, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength)
}

CWeightByMeanLinear <- function(weight, var, meantarget) {
    .Call('_drake_CWeightByMeanLinear', PACKAGE = 'drake', weight, var, meantarget)
}

anyIsNA <- function(x) {
    .Call('_drake_anyIsNA', PACKAGE = 'drake', x)
}

