# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

if(!"Rcpp" %in% loadedNamespaces()) {
    loadNamespace("Rcpp")
}

CSplitRowsByCode <- function(codes, nlevels) {
    .Call("_drake_CSplitRowsByCode", PACKAGE = "drake", codes, nlevels)
}

CClampWeights <- function(weights, max_weight, min_weight) {
    .Call("_drake_CClampWeights", PACKAGE = "drake", weights, max_weight, min_weight)
}

CApplyDensityTarget <- function(weights, match_index, sample_y, target_y) {
    .Call("_drake_CApplyDensityTarget", PACKAGE = "drake", weights, match_index, sample_y, target_y)
}

CContinuousDiffFromDensity <- function(sample_y, target_y) {
    .Call("_drake_CContinuousDiffFromDensity", PACKAGE = "drake", sample_y, target_y)
}

CBuildGaussianBasis <- function(x, xout, bw) {
    .Call("_drake_CBuildGaussianBasis", PACKAGE = "drake", x, xout, bw)
}

CWeightByContinuousBasis <- function(weights, basis, match_index, target_y) {
    .Call("_drake_CWeightByContinuousBasis", PACKAGE = "drake", weights, basis, match_index, target_y)
}

CContinuousBasisDiff <- function(weights, basis, target_y) {
    .Call("_drake_CContinuousBasisDiff", PACKAGE = "drake", weights, basis, target_y)
}

CWeightByContinuousGaussian <- function(x, weights, xout, bw, match_index, target_y) {
    .Call("_drake_CWeightByContinuousGaussian", PACKAGE = "drake", x, weights, xout, bw, match_index, target_y)
}

CContinuousGaussianDiff <- function(x, weights, xout, bw, target_y) {
    .Call("_drake_CContinuousGaussianDiff", PACKAGE = "drake", x, weights, xout, bw, target_y)
}

CWeightByDiscreteMany <- function(codes_list, weights, targets_list, cap_every_var = FALSE, max_weight = Inf, min_weight = 0) {
    .Call("_drake_CWeightByDiscreteMany", PACKAGE = "drake", codes_list, weights, targets_list, cap_every_var, max_weight, min_weight)
}

CMaxAbsDiscreteDiffMany <- function(codes_list, weights, targets_list) {
    .Call("_drake_CMaxAbsDiscreteDiffMany", PACKAGE = "drake", codes_list, weights, targets_list)
}

CWeightByDiscreteSubsetMany <- function(target_code_list, strata_code_list, weights, targets_by_strata_list, cap_every_var = FALSE, max_weight = Inf, min_weight = 0) {
    .Call("_drake_CWeightByDiscreteSubsetMany", PACKAGE = "drake", target_code_list, strata_code_list, weights, targets_by_strata_list, cap_every_var, max_weight, min_weight)
}

CWeightByDiscreteCodes <- function(codes, weights, targets) {
    .Call("_drake_CWeightByDiscreteCodes", PACKAGE = "drake", codes, weights, targets)
}

CMaxAbsDiscreteDiff <- function(codes, weights, targets) {
    .Call("_drake_CMaxAbsDiscreteDiff", PACKAGE = "drake", codes, weights, targets)
}

CWeightByDiscreteSubsetCodes <- function(target_codes, strata_codes, weights, targets_by_strata) {
    .Call("_drake_CWeightByDiscreteSubsetCodes", PACKAGE = "drake", target_codes, strata_codes, weights, targets_by_strata)
}

CMaxAbsDiscreteSubsetDiff <- function(target_codes, strata_codes, weights, targets_by_strata) {
    .Call("_drake_CMaxAbsDiscreteSubsetDiff", PACKAGE = "drake", target_codes, strata_codes, weights, targets_by_strata)
}

HiFunction <- function(k, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength) {
    .Call("_drake_HiFunction", PACKAGE = "drake", k, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength)
}

LoFunction <- function(k, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength) {
    .Call("_drake_LoFunction", PACKAGE = "drake", k, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength)
}

LoZero <- function(a, b, t, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength) {
    .Call("_drake_LoZero", PACKAGE = "drake", a, b, t, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength)
}

HiZero <- function(a, b, t, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength) {
    .Call("_drake_HiZero", PACKAGE = "drake", a, b, t, hivw, lovw, hidiff, lodiff, loweight, hiweight, meantarget, hilength, lolength)
}

CWeightByMeanLinear <- function(weight, var, meantarget) {
    .Call("_drake_CWeightByMeanLinear", PACKAGE = "drake", weight, var, meantarget)
}

anyIsNA <- function(x) {
    .Call("_drake_anyIsNA", PACKAGE = "drake", x)
}
